### ISSUE TITLE
com.facebook.react.common.JavascriptException: Error: Expected Buffer, got s, stack

### ISSUE THREAD

**Issue by DeckerSU** [VerusCoin/Verus-Mobile#62]
I tried to build app from sources, build was succeded, but after launch on device i got the following exception:
```
--------- beginning of crash
02-20 08:07:53.351  6500 15755 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
02-20 08:07:53.351  6500 15755 E AndroidRuntime: Process: com.verusmobile, PID: 6500
02-20 08:07:53.351  6500 15755 E AndroidRuntime: com.facebook.react.common.JavascriptException: Error: Expected Buffer, got s, stack:
02-20 08:07:53.351  6500 15755 E AndroidRuntime: 
02-20 08:07:53.351  6500 15755 E AndroidRuntime: 	at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:71)
02-20 08:07:53.351  6500 15755 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-20 08:07:53.351  6500 15755 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
02-20 08:07:53.351  6500 15755 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
02-20 08:07:53.351  6500 15755 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
02-20 08:07:53.351  6500 15755 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
02-20 08:07:53.351  6500 15755 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-20 08:07:53.351  6500 15755 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
02-20 08:07:53.351  6500 15755 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:246)
02-20 08:07:53.351  6500 15755 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
02-20 08:07:53.351  6500 15755 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:923)
02-20 08:07:53.354   970  6009 D NetdEventListenerService: DNS Requested by : 627, 10312
02-20 08:07:53.357   970 15794 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
02-20 08:07:53.358   970  7519 D Debug   : low && ship && 3rdparty app crash, do not dump
02-20 08:07:53.358   970  7519 W ActivityManager: crash : com.verusmobile,10312
```
Unfortunatelly, i know almost nothing about `react-native` and how i can debug this and find the root, what caused this. The only things i changed in repo before build are:

_package.json_
```
-    "react-native-vector-icons": "^6.2.0",
+    "react-native-vector-icons": "6.6.0",
```
Bcz of `toolbar-android` issue, mentioned [here ](https://github.com/oblador/react-native-vector-icons/issues/1193). And:

_android/gradle/wrapper/gradle-wrapper.properties_

```
-distributionUrl=https\://services.gradle.org/distributions/gradle-5.5-all.zip
+distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.4-all.zip
```
Bcz somehow without bump gradle it couldn't find `cargo` binary, after upgrade to `5.6.4` this issue solved.

My steps for build:

```
npm install
npm run-script dist-android
```
Also tried debug build:

```
npm install
cd android
./gradlew clean && ./gradlew assembleDebug
```
And it also end up with the exception above, right after launch app.

`react-native info`:
```
System:
    OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (4) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 457.21 MB / 7.79 GB
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 10.23.1 - /usr/bin/node
    Yarn: Not Found
    npm: 7.5.4 - ~/Verus-Mobile/node_modules/.bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK:
      Android NDK: 22.0.7026061
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 11.0.9.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: ^4.2.3 => 4.14.0 
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    *react-native*: Not Found
```

Any ideas what i could try to find a reason of the exception?

**Comment by michaeltout** [comment]
Since this comment, there have been a number of dependancy updates, including a major react native version update. I wasn't able to reproduce this when it was posted, but if the issue still occurs post react native update, and you ever retry building, please let me know.

**Comment by michaeltout** [comment]
Closing for now due to inactivity
